runtime: nodejs20
service: backend

env_variables:
  NODE_ENV: production
  PORT: 8080
  MONGO_URI: "mongodb+srv://sandeepkumar21:Sandeep933@craftconnect.2q0xiav.mongodb.net/craftconnect?retryWrites=true&w=majority&appName=Craftconnect"
  JWT_SECRET: "supersecretkey123"
  GEMINI_API_KEY: "AIzaSyAgP4XnwcyKEKun75BKqntSeEALqpi9EEM"
  ADMIN_EMAIL: "beherasandeepkumar21@gmail.com"
  ADMIN_EMAIL_APP_PASSWORD: "jtuw kthc wmvs wsiw"
  FRONTEND_ORIGIN: "https://craftconnect-hackathon-2025.uc.r.appspot.com"

handlers:
  # Serve static files from upload directory
  - url: /uploads
    static_dir: upload
    secure: always

  # All other requests go to the Node.js app
  - url: /.*
    script: auto
    secure: always

# Basic scaling for free tier
automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.6
